language: cpp
sudo: required
dist: bionic

compiler:
  - gcc
  - clang

before_install:
  # Compiler
  - if [ $CC == "gcc" ]; then export CC=gcc-9 && CXX=g++-9; fi
  - if [ $CC == "clang" ]; then export CC=clang-10 && CXX=clang++-10; fi
  # Vulkan SDK
  - sudo apt-get install vulkan-sdk
  # Check glslc
  - glslc --version

install:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --parallel 4
  - cd -

script:
  - echo "Successfully built!"

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchan-bionic-10
    packages:
      - gcc-9
      - g++-9
      - clang-10

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
